version: '3.5'
services:
  app:
    restart: always
    build: .
    depends_on:
      - mongo
    env_file: .env
    ports:
      - '3000:3000'
    volumes: 
      - ./:/app
    command: npm run devserver
  mongo:
    container_name: mongo
    image: mongo
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - mongo:/app/mongo/
volumes:
  mongo: